### ISSUE TITLE
ES Module Support

### ISSUE THREAD

**Issue by threeal** [ljharb/shell-quote#17]
Hi, will there ever be support for ES modules in this project? ES modules can be especially useful for tree-shaking, minimizing the bundle size for projects that depend on this one.

In my opinion, if this project were to support ES modules, there are two options: either support both CommonJS and ES modules or deprecate CommonJS in favor of ES modules for future versions.

**Comment by ljharb** [comment]
The project already supports ESM, because ESM can import CJS. The way it’s written doesn’t necessarily correlate to the way it’s consumed, and there’s simply zero benefit from authoring a package in native ESM.

**Comment by threeal** [comment]
I'm sorry for raising this up, but without native ES modules support, tree-shaking cannot be done. I know this library is small which mean also small benefit for tree-shaking.

But still, if there's no plan for adding a native ESM support i'll probably will republish this package in native ESM, with a different name.

**Comment by ljharb** [comment]
That’s incorrect; CJS is precisely as tree-shareable as ESM.

What benefit do you expect by using a native ESM version?

**Comment by threeal** [comment]
See https://github.com/threeal/cmake-action/pull/520.

This project is in ESM, most dependencies are also in ESM, but introducing shell-quote will require the project to add support to CJS. It works, but not ideal, for example tree-shaking cannot be done on CJS, see `dist/action.mjs`, it includes all definitions.

Anyway is it true that ESM is slower than CJS?

**Comment by ljharb** [comment]
What do you mean "add support for CJS"? Every bundler as well as node allows importing CJS from within ESM.

It's true in browsers, because of the waterfall discovery of URLs - browsers have to parse each module before they can start to load the next ones. It's true in node unless you're using the `.mjs` extension, because the `type` field slows everything down.

Tree-shaking *absolutely* can be done on CJS, _precisely_ the same as it can be done on ESM - if the tool you're using doesn't support that, then I'd suggest finding a superior tool to use.

**Comment by threeal** [comment]
Thanks for the suggestion, but i would prefer writing my own module instead rather than forcing integration on your old code.

**Comment by ljharb** [comment]
lol k, go for it ¯\\\_(ツ)_/¯
